# travis build configuration for ZeroPilot-SW

language: cpp
sudo: true

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-7-2017-q4-major

addons:
  apt:
    packages:
    - ninja-build

env:
  - TARGET=Autopilot
  - TARGET=Safety

# install cmake and google test for both linux and osx. TODO: these things should be chached
before_install: >
  if [ $TRAVIS_OS_NAME = osx ]; then
    git clone https://github.com/google/googletest
    cd googletest
    mkdir build
    cd build
    cmake ..
    make
    make install
    cd ../..
    sudo rm -r googletest;

  elif [ $TRAVIS_OS_NAME = linux ]; then
    sudo apt-get update
    sudo apt-get install cmake
    sudo apt-get install libgtest-dev
    cd /usr/src/gtest
    sudo cmake CMakeLists.txt
    sudo make
    sudo cp *.a /usr/lib
    cd $TRAVIS_BUILD_DIR;

  fi

install:
  - export GCC_DIR=$HOME/gcc-arm-none-eabi-7-2017-q4-major
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
  - export PATH=$GCC_DIR/bin:$PATH

script:
  - cd $TRAVIS_BUILD_DIR/$TARGET
  - if [ $TRAVIS_OS_NAME = linux ]; then ./Tools/build.bash -c; fi
  - if [ $TARGET = Autopilot ]; then ./Tools/build.bash -c -T; fi